library(rio)
library(stargazer)
credit_score = import("CreditRating.xlsx")
colnames(credit_score) = tolower(make.names(colnames(credit_score)))
as.factor(credit_score$student)
as.factor(credit_score$married)
as.factor(credit_score$ethnicity)
as.factor(credit_score$gender)
score1.out = lm(rating~limit+cards+student+balance,data=credit_score)
score2.out = lm(rating~limit+cards+income+ethnicity+balance,data=credit_score)
stargazer(score1.out,score2.out, type="text", single.row=TRUE)
cor(credit_score$rating, credit_score$balance)
